server:
  port: 8081

spring:
  profiles:
    active: local #default
    group:
      local:
        - common
      prod:
        - common

---
spring:
  config:
    activate:
      on-profile: common

# ...

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pre-order-service-mysql
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: sbk8689@gmail.com
    password: qcvy pemp iony egho
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

logging:
  level:
    org:
      springframework:
        security: TRACE

jwt:
  secret-key: pre-order-service-2024.secret_key
  # 30 days
  token.expired-time-ms: 2592000000

file:
  path: C:\Users\sbk86\
  url: http://localhost:4000/file/

---
spring:
  config:
    activate:
      on-profile: prod