version: "3.8"
services:
  pre-order-service-mysql:
    container_name: pre-order-service-mysql
    build:
      dockerfile: Dockerfile
      context: ./database
    image: sbk8689/pre-order-service-mysql
    environment:
      - MYSQL_DATABASE=pre-order-service-mysql
      - MYSQL_ROOT_PASSWORD=${SPRING_DATABASE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
    ports:
      - "3306:3306"

