server:
  port: 8082

spring:
  profiles:
    active: local #default
    group:
      local:
        - common
      prod:
        - common

---
spring:
  config:
    activate:
      on-profile: common

# ...

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pre-order-service-mysql
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: sbk8689@gmail.com
    password: qcvy pemp iony egho
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  application:
    name: newsFeed-service

logging:
  level:
    org:
      springframework:
        security: TRACE

jwt:
  secret-key: pre-order-service-2024.secret_key
  # 30 days
  token.expired-time-ms: 2592000000

file:
  path: C:\Users\sbk86\
  url: http://localhost:4000/file/

feign:
  url:
    prefix: http://localhost:8080/
  client:
    config:
      default:
        connectTimeout: 1000
      user-service:
        connectTimeout: 1000

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true #eureka 서버로부터 인스턴스들의 정보를 주기적으로 가져올 것인지 설정하는 속성. true이면 갱신된 정보를 받겠다는 설정
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  config:
    activate:
      on-profile: prod